### ISSUE TITLE
Error on CocRestart

### ISSUE THREAD

**Issue by GrassHopper42** [weirongxu/coc-helper#9]
When I Run `:CocRestart`, it occur following error message

```
Error on notification runCommand Error: Command: coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 not found
```

In `:CocOpenLog`

```
2022-12-16T01:08:15.472 INFO (pid:74974) [attach] - receive notification: runCommand [
   ^[[32m'coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3'^[[39m,
   ^[[32m'CocGitStatusChange'^[[39m
 ]
 2022-12-16T01:08:15.473 ERROR (pid:74974) [attach] - Error on notification runCommand Error: Command: coc-helper.internal.didVimEvent_m2_v0_15_2_explorer_3 not found
     at Sk.executeCommand (/Users/grasshopper42/.vim/plugged/coc.nvim/build/index.js:69:3935)
     at Sk.fireCommand (/Users/grasshopper42/.vim/plugged/coc.nvim/build/index.js:69:4101)
 ^[[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)^[[39m
     at async mm.runCommand (/Users/grasshopper42/.vim/plugged/coc.nvim/build/index.js:261:24114)
     at async Wm.cocAction (/Users/grasshopper42/.vim/plugged/coc.nvim/build/index.js:281:47124)
     at async EventEmitter.<anonymous> (/Users/grasshopper42/.vim/plugged/coc.nvim/build/index.js:281:48851)```

**Comment by weirongxu** [comment]
I have removed the custom vim events from coc-helper and used the coc autocmd module on coc-explorer and coc-floatinput instead of it.
This bug no longer exists.
